version: "3.5"

services: 
    neo4j:
        image: neo4j:4.2.4
        container_name: neo4j
        ports: 
            - 7474:7474
            - 7687:7687
        volumes: 
            - db:/data
    redis:
        image: redis
        container_name: redis
        ports: 
            - 6379:6379
        volumes: 
            - db:/data
volumes: 
    db:
        external: true